### ISSUE TITLE
multi stable

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/chain#139]

**Comment by YasunoriMATSUOKA** [comment]
@mkXultra  
- [ ] Implement the case collateral is ubtc and cdp is euu pegged to EURO.
- [ ] Do not hardcode `euu`. In order to be able to increase the number of supported cdp's by adding them to the genesis.json configuration without any changes to the code.

cc: @KimuraYu45z 
Plz follow if you need anything.

**Comment by YasunoriMATSUOKA** [comment]
Status

- [x] Implementation
- [x] Go build
- [x] Docker image build with GitHub Actions CD
- [ ] Deploy on private testnet
- [ ] Debug

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z @mkXultra 
プライベートテストネットを起動しようとしているのですが、`docker-compose up -d` で起動しようとすると(= start を実行に相当)、以下のようにpanicでノードが正常に起動する前に落ちてしまう状況です。

<details>

```
~/ununifi$ docker-compose up -d
Creating ununifid ... done
ununifi@jpyx-a:~/ununifi$ docker logs ununifid
10:19AM INF starting ABCI with Tendermint
10:19AM INF Starting multiAppConn service impl=multiAppConn module=proxy
10:19AM INF Starting localClient service connection=query impl=localClient module=abci-client
10:19AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
10:19AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
10:19AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
10:19AM INF Starting EventBus service impl=EventBus module=events
10:19AM INF Starting PubSub service impl=PubSub module=pubsub
10:19AM INF Starting IndexerService service impl=IndexerService module=txindex
10:19AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=develop-a09038ab9a36078f55eed395e5f0cddded98bb06
10:19AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
10:19AM INF asserting crisis invariants inv=0/12 module=x/crisis name=bank/nonnegative-outstanding
10:19AM INF asserting crisis invariants inv=1/12 module=x/crisis name=bank/total-supply
10:19AM INF asserting crisis invariants inv=2/12 module=x/crisis name=gov/module-account
10:19AM INF asserting crisis invariants inv=3/12 module=x/crisis name=distribution/nonnegative-outstanding
10:19AM INF asserting crisis invariants inv=4/12 module=x/crisis name=distribution/can-withdraw
10:19AM INF asserting crisis invariants inv=5/12 module=x/crisis name=distribution/reference-count
10:19AM INF asserting crisis invariants inv=6/12 module=x/crisis name=distribution/module-account
10:19AM INF asserting crisis invariants inv=7/12 module=x/crisis name=liquidity/escrow-amount
10:19AM INF asserting crisis invariants inv=8/12 module=x/crisis name=staking/module-accounts
10:19AM INF asserting crisis invariants inv=9/12 module=x/crisis name=staking/nonnegative-power
10:19AM INF asserting crisis invariants inv=10/12 module=x/crisis name=staking/positive-delegation
10:19AM INF asserting crisis invariants inv=11/12 module=x/crisis name=staking/delegator-shares
10:19AM INF asserted all invariants duration=2.047424 height=0 module=x/crisis
10:19AM INF created new capability module=ibc name=ports/transfer
10:19AM INF port binded module=x/ibc/port port=transfer
10:19AM INF claimed capability capability=1 module=transfer name=ports/transfer
panic: ubtc collateral not found in pricefeed

goroutine 1 [running]:
github.com/UnUniFi/chain/x/cdp.InitGenesis({{0x2147be8, 0xc000054170}, {0x2175a00, 0xc000c03b80}, {{0x0, 0x0}, {0xc000c8e168, 0x16}, 0x0, {0x1da539d4, ...}, ...}, ...}, ...)
        github.com/UnUniFi/chain/x/cdp/genesis.go:40 +0x10b4
github.com/UnUniFi/chain/x/cdp.AppModule.InitGenesis({{{0x217b5b8, 0xc000d2b1b0}}, {{0x217b5b8, 0xc000d2b1b0}, {0x21125f0, 0xc000be67d0}, {0x21125f0, 0x0}, {{0x2170138, 0xc000d2b1b0}, ...}, ...}, ...}, ...)
        github.com/UnUniFi/chain/x/cdp/module.go:156 +0x15e
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2147be8, 0xc000054170}, {0x2175a00, 0xc000c03b80}, {{0x0, 0x0}, {0xc000c8e168, 0x16}, 0x0, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.0/types/module/module.go:320 +0x29d
github.com/UnUniFi/chain/app.(*App).InitChainer(_, {{0x2147be8, 0xc000054170}, {0x2175a00, 0xc000c03b80}, {{0x0, 0x0}, {0xc000c8e168, 0x16}, 0x0, ...}, ...}, ...)
        github.com/UnUniFi/chain/app/app.go:777 +0x1d2
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0000b49c0, {{0x1da539d4, 0xed99c0957, 0x0}, {0xc000c8e168, 0x16}, 0xc000c99cc0, {0x30ea080, 0x0, 0x0}, ...})
        github.com/cosmos/cosmos-sdk@v0.45.0/baseapp/abci.go:62 +0x475
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000d143c0, {{0x1da539d4, 0xed99c0957, 0x0}, {0xc000c8e168, 0x16}, 0xc000c99cc0, {0x30ea080, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xd8, {{0x1da539d4, 0xed99c0957, 0x0}, {0xc000c8e168, 0x16}, 0xc000c99cc0, {0x30ea080, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x20db330, 0x8}}, {0xc000c8e168, 0x16}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0xd98
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001095e58, {0x2176f68, 0xc000b64000})
        github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x20db330, 0x8}}, {0xc000c8e168, 0x16}, 0x1, 0x0, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000ee8780, {0x21230d0, 0xc000148a00}, 0xc000c82810, {0x2103c40, 0xc00000ea20}, 0x0, 0x0, 0xc000c82970, {0x21489b0, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x2151350, 0xc000d2b1b0}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.0/server/start.go:263 +0x7c5
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000f1f180, {0x30ea080, 0x0, 0x0})
        github.com/cosmos/cosmos-sdk@v0.45.0/server/start.go:129 +0x193
github.com/spf13/cobra.(*Command).execute(0xc000f1f180, {0x30ea080, 0x0, 0x0})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ce8500)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc000c630c0, 0xe})
        github.com/cosmos/cosmos-sdk@v0.45.0/server/cmd/execute.go:36 +0x1eb
main.main()
        github.com/UnUniFi/chain/cmd/ununifid/main.go:13 +0x2c
```

</details>

手順に問題があったり、genesis.jsonに問題があったりといった可能性もありえると思っているのですが、まずはいったん取り急ぎ情報共有させてもらいます。

何か考えられる問題点等あれば、共有頂けるととても助かります。

デバッグの際に利用しているgenesis.jsonはこちらになります。

https://github.com/UnUniFi/chain/blob/develop/launch/ununifi-8-private-test/genesis-pretty.json

@mkXultra 
もしgenesis.jsonの中にこれが足りないとか、keyがこう変わっているはずとか、valueがこう変わっていないとダメ等あれば、フォロー頂けるととても助かります。お手数ですがよろしくお願いします。

**Comment by KimuraYu45z** [comment]
```
goroutine 1 [running]:
github.com/UnUniFi/chain/x/cdp.InitGenesis({{0x2147be8, 0xc000054170}, {0x2175a00, 0xc000c03b80}, {{0x0, 0x0}, {0xc000c8e168, 0x16}, 0x0, {0x1da539d4, ...}, ...}, ...}, ...)
        github.com/UnUniFi/chain/x/cdp/genesis.go:40 +0x10b4
```

`github.com/UnUniFi/chain/x/cdp/genesis.go:40`とあるので

https://github.com/UnUniFi/chain/blob/main/x/cdp/genesis.go#L40

ここですね。

**Comment by mkXultra** [comment]
@YasunoriMATSUOKA 
すみません
見逃していました
基本的に以下のスクリプトを走らせるとスタートできると思います
jqで変えている部分の改変が必要です
```
ununifid unsafe-reset-all;
ununifid init miyagi-chain --chain-id ununifi-6-test-private;
sed -i '/\[api\]/,+3 s/enable = false/enable = true/' ~/.ununifi/config/app.toml;
sed -i 's/stake/uguu/g' ~/.ununifi/config/genesis.json;
jq '.app_state.cdp.params.collateral_params =[{ "auction_size": "50000000000", "conversion_factor": "6", "debt_limit": { "amount": "20000000000000", "denom": "jpu" }, "denom": "ubtc", "liquidation_market_id": "ubtc:jpy:30", "liquidation_penalty": "0.075000000000000000", "liquidation_ratio": "1.500000000000000000", "prefix": 0, "spot_market_id": "ubtc:jpy", "stability_fee": "1.000000001547125958", "type": "ubtc-a", "check_collateralization_index_count": "1000", "keeper_reward_percentage": "0.000001" },{"auction_size": "50000000000", "conversion_factor": "6","debt_limit": {"amount":"20000000000000","denom": "euu" },"denom": "ubtc", "liquidation_market_id": "ubtc:eur:30",  "liquidation_penalty": "0.075000000000000000",  "liquidation_ratio": "1.500000000000000000",  "prefix": 1,  "spot_market_id": "ubtc:eur",  "stability_fee": "1.000000001547125958",  "type": "ubtc-b",  "check_collateralization_index_count": "1000", "keeper_reward_percentage": "0.000001"}]'  ~/.ununifi/config/genesis.json > temp.json ; mv temp.json ~/.ununifi/config/genesis.json;
jq '.app_state.cdp.params.debt_params[0].global_debt_limit.amount = "200000000000000"'  ~/.ununifi/config/genesis.json > temp.json ; mv temp.json ~/.ununifi/config/genesis.json;
jq '.app_state.cdp.params.debt_params[1].global_debt_limit.amount = "200000000000000"'  ~/.ununifi/config/genesis.json > temp.json ; mv temp.json ~/.ununifi/config/genesis.json;
jq '.app_state.pricefeed.params.markets = [{ "market_id": "ubtc:jpy", "base_asset": "ubtc", "quote_asset": "jpy", "oracles": [ "ununifi1a8jcsmla6heu99ldtazc27dna4qcd4jygsthx6" ], "active": true }, { "market_id": "ubtc:jpy:30", "base_asset": "ubtc", "quote_asset": "jpy", "oracles": [ "ununifi1a8jcsmla6heu99ldtazc27dna4qcd4jygsthx6" ], "active": true }, { "market_id": "ubtc:eur", "base_asset": "ubtc", "quote_asset": "eur", "oracles": [ "ununifi1a8jcsmla6heu99ldtazc27dna4qcd4jygsthx6" ], "active": true }, { "market_id": "ubtc:eur:30", "base_asset": "ubtc", "quote_asset": "eur", "oracles": [ "ununifi1a8jcsmla6heu99ldtazc27dna4qcd4jygsthx6" ], "active": true }]'  ~/.ununifi/config/genesis.json > temp.json ; mv temp.json ~/.ununifi/config/genesis.json;
ununifid keys add my_validator --recover < mnt.txt;
ununifid add-genesis-account my_validator 100000000000uguu,100000000000ubtc;
ununifid gentx my_validator 100000000uguu --chain-id ununifi-6-test-private --keyring-backend test;
ununifid collect-gentxs;
```

**Comment by mkXultra** [comment]
ニーモニックを共有しようと思っていたら消してしまっていたので、アドレスの部分は書き換えが必要です。

**Comment by mkXultra** [comment]
ニーモニックありました
以下の一行をmnt.txtとして保存して実行してください
```
figure web rescue rice quantum sustain alert citizen woman cable wasp eyebrow monster teach hockey giant monitor hero oblige picnic ball never lamp distance
```

**Comment by YasunoriMATSUOKA** [comment]
忘れないようにメモ
collateral_paramsの配列の中の各要素のprefixを0始まりでなく、1始まりにしてしまっているのがNGな気がする

**Comment by mkXultra** [comment]
@YasunoriMATSUOKA 
> デバッグの際に利用しているgenesis.jsonはこちらになります。
https://github.com/UnUniFi/chain/blob/develop/launch/ununifi-8-private-test/genesis-pretty.json

エラー見るとpricefeedが無いのが原因だと思います
ubtc:eurのPricefeedが定義されていないようです
https://github.com/UnUniFi/chain/blob/3d14048a9cdf0811be206b2eab726acb8e0f50a8/launch/ununifi-8-private-test/genesis-pretty.json#L289

**Comment by YasunoriMATSUOKA** [comment]
@mkXultra 
以下のご指摘、完璧な助言でした。ありがとうございました！
https://github.com/UnUniFi/chain/issues/139#issuecomment-1042890351
