### ISSUE TITLE
[derivatives] consensus failure after the tx of open-position

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/chain#369]
when you execute `open-position` tx, you get success response at that time.

but, after a few moments, the chain stops due to the consensus failure with these messages.

```shell
ERR CONSENSUS FAILURE!!! err="runtime error: invalid memory address or nil pointer dereference" module=consensus stack="goroutine 177 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x64\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:727 +0x44\npanic({0x1027fd880, 0x103adf880})\n\truntime/panic.go:884 +0x204\nmath/big.(*Int).Mul(0x14003780520, 0x14003780520, 0x0)\n\tmath/big/int.go:167 +0xac\ngithub.com/cosmos/cosmos-sdk/types.Dec.MulMut({0x140018d19f8?}, {0x1005b890c?})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.0/types/decimal.go:289 +0x28\ngithub.com/cosmos/cosmos-sdk/types.Dec.ImmutOp({0x1027d7320?}, 0x102abb9f0, {0x140041d9400?})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.0/types/decimal.go:232 +0x15c\ngithub.com/cosmos/cosmos-sdk/types.Dec.Mul(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.0/types/decimal.go:284\ngithub.com/UnUniFi/chain/x/derivatives.levyImaginaryFundingRate({{0x102ae6290, 0x1400019e008}, {0x102af70e0, 0x140038b59c0}, {{0xb, 0x0}, {0x140042b81fc, 0x4}, 0x97, {0x237a3eb0, ...}, ...}, ...}, ...)\n\tgithub.com/UnUniFi/chain/x/derivatives/abci.go:34 +0x3ac\ngithub.com/UnUniFi/chain/x/derivatives.BeginBlocker(...)\n\tgithub.com/UnUniFi/chain/x/derivatives/abci.go:70\ngithub.com/UnUniFi/chain/x/derivatives.AppModule.BeginBlock(...)\n\tgithub.com/UnUniFi/chain/x/derivatives/module.go:159\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x102ae6290, 0x1400019e008}, {0x102af70e0, 0x140038b59c0}, {{0xb, 0x0}, {0x140042b81fc, 0x4}, 0x97, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.0/types/module/module.go:481 +0x2b0\ngithub.com/UnUniFi/chain/app.(*App).BeginBlocker(_, {{0x102ae6290, 0x1400019e008}, {0x102af70e0, 0x140038b59c0}, {{0xb, 0x0}, {0x140042b81fc, 0x4}, 0x97, ...}, ...}, ...)\n\tgithub.com/UnUniFi/chain/app/app.go:941 +0x60\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0x14004e4c520, 0x20, 0x20}, {{0xb, 0x0}, {0x140042b81fc, 0x4}, 0x97, {0x237a3eb0, ...}, ...}, ...})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.0/baseapp/abci.go:200 +0x6ac\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0x14004e4c520, 0x20, 0x20}, {{0xb, 0x0}, {0x140042b81fc, 0x4}, 0x97, {0x237a3eb0, ...}, ...}, ...})\n\tgithub.com/tendermint/tendermint@v0.34.20/abci/client/local_client.go:280 +0x108\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0x14004e4c520, 0x20, 0x20}, {{0xb, 0x0}, {0x140042b81fc, 0x4}, 0x97, {0x237a3eb0, ...}, ...}, ...})\n\tgithub.com/tendermint/tendermint@v0.34.20/proxy/app_conn.go:81 +0x4c\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x102ae73a0?, 0x14000ed9020}, {0x102aef0b0, 0x14001851d20}, 0x14001584000, {0x102af5d10, 0x14001850cd0}, 0x96?)\n\tgithub.com/tendermint/tendermint@v0.34.20/state/execution.go:307 +0x2b8\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x14000059ba0, 0x8}}, {0x14000059ba8, 0x4}, 0x1, 0x96, {{0x140047045a0, ...}, ...}, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.34.20/state/execution.go:140 +0xe4\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x14001622a80, 0x97)\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:1655 +0x94c\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x14001622a80, 0x97)\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:1564 +0x288\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:1499 +0x90\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0x14001622a80, 0x97, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:1537 +0xb8c\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0x14001622a80, 0x1400482a460, {0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:2151 +0x1678\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x14001622a80, 0x1400482a460, {0x0?, 0x1006234bc?})\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:1949 +0x28\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x14001622a80, {{0x102ac8760?, 0x1400019a110?}, {0x0?, 0x0?}})\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:856 +0x108\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x14001622a80, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:783 +0x368\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.20/consensus/state.go:379 +0xf4\n"

```

**Comment by taiki1frsh** [comment]
the logics inside BeginBlock were moved out.
So, this error doesn't occur at BeginBlock now.
But, the problem itself that caused this error is still unsure to be solved.
